apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: krashmina612/cloudkitchen-auth-service:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: "mongodb+srv://krashmina612:ck1234@ck-cluster.ftvzrdo.mongodb.net/CK-DB?retryWrites=true&w=majority"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: ACCESS_TOKEN_SECRET
              value: "your_access_token_secret"
            - name: REFRESH_TOKEN_SECRET
              value: "secretkeyforrefreshtoken"
            - name: ACCESS_TOKEN_EXPIRE_TIME
              value: "1h"
            - name: REFRESH_TOKEN_EXPIRE_TIME
              value: "5d"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
