apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: krashmina612/cloudkitchen-order-service:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb+srv://krashmina612:ck1234@ck-cluster.ftvzrdo.mongodb.net/CK-DB?retryWrites=true&w=majority"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
