apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: krashmina612/cloudkitchen-restaurant-service:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              value: "mongodb+srv://krashmina612:ck1234@ck-cluster.ftvzrdo.mongodb.net/CK-DB?retryWrites=true&w=majority"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"


---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
